config/routes.rb
Rails.application.routes.draw do
  root :to => 'tales#index'
  resources :tales do
    collection do
      get 'images'
    end
    resources :contributions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  validates :content, :presence => true
  validates :username, :presence => true
  belongs_to :tale

end

app/models/tale.rb
class Tale < ActiveRecord::Base
  validates :title, :presence => true
  has_many :contributions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def random_image
    return Random.new.rand(158)
  end
  def all_images
    images = []
    (1..158).each() do |t|
      images.push(t)
    end
    return images
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  def show
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
  end
  def new
    @tale = Tale.find(params[:tale_id])
    @image = random_image
    @contribution = Contribution.new
  end
  def create
    @tale = Tale.find(params[:tale_id])
    @contribution = @tale.contributions.new(contribution_params)
    if @contribution.save
      flash[:notice]="You have added a contribution!"
      redirect_to tale_path(@tale)
    else
      flash[:alert]="Oops, something went wrong...try again!"
      render :new
    end
  end
  def edit
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
  end
  def update
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
      if @contribution.update(contribution_params)
        flash[:notice]="You have updated your contribution!"
        redirect_to tale_path(@tale)
      else
        flash[:alert]="Oops, something went wrong...try again!"
        render :edit
      end
    end
    def destroy
      @tale = Tale.find(params[:tale_id])
      @contribution = Contribution.find(params[:id])
      @contribution.destroy
      redirect_to tale_path(@tale)
    end



private
  def contribution_params
  params.require(:contribution).permit(:content, :username, :image)
  end
end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  def index
    @tales = Tale.all
    if params[:order] == 'title'
      @tales = Tale.all.order('title')
    end
  end

  def show
    @tale = Tale.find(params[:id])
  end

  def new
    @tale = Tale.new
  end

  def create
    @tale = Tale.new(tale_params)
    if @tale.save
      flash[:notice]="You have added a tale!"
      redirect_to tales_path
    else
      flash[:alert]="Oops, something went wrong...try again!"
      render :new
    end
  end

  def edit
    @tale = Tale.find(params[:id])
  end
  def update
    @tale = Tale.find(params[:id])
    if @tale.update(tale_params)
      flash[:notice]="You have updated your tale!"
      redirect_to tale_path(@tale)
    else
      flash[:alert]="Oops, something went wrong...try again!"
      render :edit
    end
  end
  def destroy
    @tale = Tale.find(params[:id])
    @tale.destroy
    redirect_to tales_path
  end
  def images
    @images = all_images
  end

private
  def tale_params
    params.require(:tale).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributions/_form.html.erb
<%= render "layouts/errors", :object => @contribution %>
<div class="well">
<%= image_tag @image %>
<%= form_for [@tale, @contribution] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>
  <%= f.hidden_field :image, :value => @image %>
  <%= f.submit class: 'btn btn-primary'%>
</div>
<% end %>

app/views/contributions/edit.html.erb
<h1 class="title"> Edit Contribution:</h1>
<%= render "layouts/errors", :object => @contribution %>
<div class="well">
<%= image_tag @contribution.image %>
<%= form_for [@tale, @contribution] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>
  <%= f.hidden_field :image, :value => @contribution.image %>
    <%= f.submit class: 'btn btn-primary'%>

</div>


<% end %>

app/views/contributions/new.html.erb
<h1 class="title">Contributing to: <%= @tale.title %></h1>
  <% if @tale.contributions.any? %>
  <div class="well">
  <h3>The Story So Far:</h3>
  </div>
  <% @tale.contributions.each do  |contrib| %>
  <div class="well">
  <p> <%= image_tag contrib.image %>  <%= contrib.content%></p>
  <p> written by: <%= contrib.username %> </p>
</div>
  <% end %>
  <% else %>
  <div class="well">
  <p> There is nothing to this tale! Add something! </p>
</div>
  <% end %>
<%= render "form" %>

app/views/contributions/show.html.erb
<h1 class="title"> <%= @tale.title %> </h1>
<div class="well">
<%= image_tag @contribution.image %>
<h5><%= @contribution.content %></h5>
<h5><%= @contribution.username %></h5>
</div>

<div class="row">
  <div class="col-md-6">
    <%= button_to "Edit this contribution", edit_tale_contribution_path(@tale, @contribution), :method => :get, class: "btn btn-success"  %>
  </div>
  <div class="col-md-6">
<%= button_to "Delete contribution", tale_contribution_path(@tale, @contribution), :method => :delete, class: "btn btn-danger",
              :data => {:confirm => "Are you sure? It was a good one.",
              :method => "delete"}%>
    </div>

<div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebTales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
        <h4 class="navbar-brand"> <%= link_to "Web Tales", tales_path %> </h4>
      </div>
        <ul class=" navbar-brand nav  navbar-right">
          <li><%= link_to "All Images", images_tales_url %></li>
        </ul>
      </div>
    </nav>
  </head>

  <body>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash[:notice] %>">
          <%= value %>
        </div>
        <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/tales/_form.html.erb
<%= render "layouts/errors", :object => @tale %>
<div class="well">
<%= form_for @tale do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary'%>
</div>
<% end %>

app/views/tales/edit.html.erb
<h1 class="title">Edit <%= @tale.title %> </h1>

<%= render "form" %>

app/views/tales/images.html.erb
<h1 class="title">Here are all of the possible images that you can get!</h1>
<div class="image-container">
<% @images.each do |image| %>
 <%= image_tag image %>
<% end %>
</div>

app/views/tales/index.html.erb
<div id="title-page">
  <h1>Welcome to Web Tales!</h1>
  <h6>(Woo-hoo!)</h6>
</div>
<div class="well">
<p> Web Tales is a web-app were people come and post single sentences inspired by a randomized image. Tales of derring, bad, and good luck tales. Its up to you to come up with it!
</p>
</div>
<div class="well">
  <h2>List 'O Tales:</h2>
  <%@tales.order(created_at: :desc).each do |tale|%>
  <h4><%= link_to tale.title, tale_path(tale) %></h4>
<%end%>
</div>
<div class="row">
  <div class="col-md-4">
    <h6> <%= button_to "Add a new web tale", new_tale_path, :method => :get, class: "btn btn-info"  %> </h6>
  </div>
  <div class="col-md-4">
    <%= link_to "Order by title", tales_path(order: 'title'), :method => :get, class: "btn btn-filter"  %>
  </div>
  <div class="col-md-4">
    <%= link_to "Order by recently created", tales_path, :method => :get, class: "btn btn-warning"  %>
  </div>
</div>

app/views/tales/new.html.erb
<h1 class="title">A new tale:</h1>

<%= render "form" %>

app/views/tales/show.html.erb
<h1 class="title"><%= @tale.title %></h1>

<% if @tale.contributions.any? %>
<% @tale.contributions.each do |c|  %>
    <div class="well">
      <p><%= image_tag c.image %></p>
      <p><%= c.content %></p>
      <p>Written by: <%= c.username %></p>
      <%= link_to "View Details", tale_contribution_path(@tale, c)%>
    </div>
    <% end %>
  <% else %>
  <div class="well">
    <p>There is nothing here yet!</p>
  </div>
<% end %>
<div class="row">
  <div class="col-md-4">
    <%= button_to "Add a contribution",  new_tale_contribution_path(@tale), :method => :get, class:"btn btn-info" %>
  </div>
  <div class="col-md-4">
    <%= button_to "Edit this title", edit_tale_path(@tale), :method => :get, class: "btn btn-success " %>
  </div>
  <div class="col-md-4">
    <%= button_to "Delete this tale", tale_path(@tale), :method => :delete, class: "btn btn-danger ",
                                                                  :data => {:confirm => "Are you sure?",
                                                                            :method => "delete"}%>
  </div>
</div>